version: '3'
services:
    postgres:
        image: postgres:11-alpine
        volumes:
            - ./docker/postgres/data:/var/lib/postgresql/data
            - ./docker/postgres/config:/etc/postgresql  # Добавляем volume для конфигурации
        environment:
            - POSTGRES_DB=gophermart
            - POSTGRES_USER=developer
            - POSTGRES_PASSWORD=developer
        ports:
            - 5432:5432
        networks:
            - net
    rabbitmq:
        build: ./docker/rabbit
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - net
        restart: always
networks:
    net:
        driver: bridge
